//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jeu_du_pendu_Bettache
{
    using System;
    using System.Collections.Generic;
    
    public partial class dictionnaire
    {
        public string mot { get; set; }
        public string langue { get; set; }
        public string niveau { get; set; }
    }
}
